### ISSUE TITLE
Vaadin Flow

### ISSUE THREAD

**Issue by F43nd1r** [mstahv/jfreechartwrapper#3]
Are there any plans to provide a flow-compatible version of this?

**Comment by mstahv** [comment]
It shouldn't be too hard to implement that, but so far I haven't heard anybody working on this. 

Want to give it a try?

**Comment by F43nd1r** [comment]
I already did. https://github.com/F43nd1r/Acrarium/blob/master/src/main/java/com/faendir/acra/ui/base/JFreeChartWrapper.java
Works for my usecase. I've stripped a lot of features though.

**Comment by mstahv** [comment]
Cool! Maybe package it to vaadin.com/directory and share it with the community?

**Comment by F43nd1r** [comment]
I might do that in the future. Right now I would have to reverseengineer the maven build to be able to do it in gradle. As I'm not familiar with maven, I'll wait for https://github.com/devsoap/gradle-vaadin-flow to support directory packaging.

**Comment by mstahv** [comment]
Want some help? I can do the initial project setup for you.

**Comment by F43nd1r** [comment]
sure. I've set up https://github.com/F43nd1r/vaadin-jfreechart-flow and added you as a collaborator.

**Comment by mstahv** [comment]
Awesome. The zip file here should be now a properly prepared for Directory release:

https://github.com/F43nd1r/vaadin-jfreechart-flow/releases/tag/jfreechart-flow-1.0

Let me know if there is some issue with it. I'll still add some small instructions to README.md

**Comment by F43nd1r** [comment]
I've uploaded it to the [vaadin directory](https://vaadin.com/directory/component/jfreechart-flow). What is the best way to get it to maven central as well?

**Comment by mstahv** [comment]
Awesome, big thanks!

You'll need to sign the artifacts and then deploy them somehow. Sonatype provides a way for generic OSS projects to publish to Maven central. I have been using that for some artifacts (and we are using this also for vaadin core too):

https://central.sonatype.org/pages/ossrh-guide.html

I think you are basically missing a unique groupId/domain, account to oss sonatype, signing and deploying. There is bit of a hassle to get all set up, but after the first release to Maven central, everything should be rather straightforward.

BTW. @samie, can we change the groupId of an existing artifact in vaadin.com/directory ? The groupId for example this project is org.vaadin.addon and I guess that makes it bit difficult to push that to Maven central 🤔

**Comment by F43nd1r** [comment]
I've tried to set up all of that, and it almost works. The only problem is that it tries to upload the directory zip to maven as well, which fails with 
```
Missing Signature: '/com/faendir/vaadin/jfreechart-flow/1.1.4/jfreechart-flow-1.1.4-jfreechart-wrapper.zip.asc' does not exist for 'jfreechart-flow-1.1.4-jfreechart-wrapper.zip'.
```

How can I exclude that file/otherwise fix this?

**Comment by mstahv** [comment]
You'd need to sign that artifact as well, but actually you shouldn't need to publish that to Maven central at all. The zip file is only there for proper vaadin.com/directly publishing. 

I added a blind commit to your project, I hope that resolves the issue.  Maven assembly plugin isn't too well documented, but if I got the terminology right, I believe zip file is now not included in deployment artifacts (but still created for vaadin.com/directory publishing). Let me know if it works or not!

**Comment by F43nd1r** [comment]
I know it doesn't belong on maven, that's why I asked for a way to exclude it. I don't see your commit, have you pushed it already?

**Comment by mstahv** [comment]
Ah, sorry. Forgot the git push 🙈

**Comment by F43nd1r** [comment]
Alright, after several timeouts the upload worked. Maybe you could link from this project to my flow version? Automated directory upload isn't possible, right? 
Anyways, thanks for the help.

**Comment by mstahv** [comment]
I'll add links in a moment.

We have an enhancement idea for the directory, so that it could be automated as well, but so far there has been other things on top of the TODO list. Ping @samie ;-)

Thanks for pushing out the add-on, I'm sure it will help many Vaadin developers!
